"""One-time reconciliation: re-writes every already-written facts/
submissions Parquet file through the now-fixed, explicit-PyArrow-schema
write path (store.py's own _write_parquet) -- pure re-encoding, no content
changes. Needed because files written before that fix could have a column
(most commonly start_date, in a partition covering only instant facts)
inferred as PyArrow's special `null` type instead of `string` -- harmless
for that one file alone, but DuckDB's read_parquet() then refuses to
combine it with another partition whose start_date is a real string
("Conversion Error: ... VARCHAR -> NULL"). Confirmed live against the
exact reported failure; see schema.py's own docstring for the full
mechanism.

Pure R2 read + re-write, NO SEC network calls -- safe to run any time,
and cheap even across the full curated universe's history.

Run this BEFORE scripts/rebuild_sec_financials.py: this script only fixes
facts/submissions (the two layers with no other source to rebuild from);
financials gets fully regenerated by that separate script anyway (and
picks up the new start_date/end_date columns -- see schema.py -- in the
same pass), so there's nothing to reconcile there directly.

Usage:
    uv run python scripts/reconcile_sec_parquet_schema.py
"""
from __future__ import annotations

from tam.research.data.sec.store import SecStore


def main() -> None:
    store = SecStore()

    facts_partitions = sorted(store.list_facts_partitions())
    print(f"{len(facts_partitions)} facts partition(s) to reconcile.")
    for taxonomy, fiscal_year in facts_partitions:
        df = store.read_facts(taxonomy, fiscal_year)
        store._write_parquet(store._facts_key(taxonomy, fiscal_year), df)
        print(f"  reconciled facts/{taxonomy}/{fiscal_year}.parquet ({len(df)} row(s))")

    submissions_partitions = sorted(store.list_submissions_partitions())
    print(f"{len(submissions_partitions)} submissions partition(s) to reconcile.")
    for fiscal_year in submissions_partitions:
        df = store.read_submissions(fiscal_year)
        store._write_parquet(store._submissions_key(fiscal_year), df)
        print(f"  reconciled submissions/{fiscal_year}.parquet ({len(df)} row(s))")

    print("Done. Now run scripts/rebuild_sec_financials.py to regenerate financials with the fixed schema.")


if __name__ == "__main__":
    main()
