project = "tam"
copyright = "Ehud Adler"
author = "Ehud Adler"

extensions = ["myst_parser", "sphinx.ext.autodoc"]
myst_enable_extensions = ["colon_fence"]
myst_heading_anchors = 3

# myst_heading_anchors generates a real HTML id for every heading (so
# cross-file links like `file.md#some-heading` work in the rendered
# site), but MyST's own xref validator doesn't check those auto-generated
# ids against other documents, so it warns anyway even though the link
# is correct. "ref.python" is a different, unrelated false positive:
# autodoc renders every `Registry.register/get/create(base_type: type,
# ...)` signature (tam/registry.py) verbatim, and Sphinx's Python domain
# tries to hyperlink the bare builtin `type` annotation to a LOCAL
# project attribute of the same name instead of Python's own `type` --
# there happen to be three unrelated classes with a `type` attribute
# (tam.discovery.upload.UploadResult.type, its re-export, and
# tam.events.types.Event.type), so it can't disambiguate and warns on
# every page that renders a Registry-touching signature (confirmed live:
# 45 identical warnings, one per affected page). Nothing to fix -- the
# annotation is correct and the pages render fine either way.
suppress_warnings = ["myst.xref_missing", "ref.python", "docutils"]

# docs/api/*.rst is generated by `sphinx-apidoc -o docs/api tam --separate
# --module-first -f` (run in CI right before sphinx-build, see
# .github/workflows/docs.yml) -- not checked in, not hand-edited.
source_suffix = {".md": "markdown", ".rst": "restructuredtext"}

# autodoc actually IMPORTS every module to read its docstrings/signatures
# (unlike e.g. sphinx-autoapi) -- these are exactly the optional-extra
# dependencies from pyproject.toml's [project.optional-dependencies] that
# the docs build never installs (mlx_lm in particular is Mac-only and
# can't install on the Linux CI runner at all). Mocking them here is the
# standard Sphinx mechanism for "don't require a heavy/platform-specific
# dependency just to extract a docstring" -- confirmed safe because this
# codebase already imports every one of these LAZILY inside functions,
# not at module top level, except tam/strategy/mlx_lora_client.py, which
# imports mlx_lm eagerly (tam/strategy/__init__.py wraps importing THAT
# WHOLE SUBMODULE in a try/except for exactly this reason, but
# sphinx-apidoc generates a stub targeting mlx_lora_client directly,
# bypassing that guard).
autodoc_mock_imports = [
    "boto3",
    "botocore",
    "duckdb",
    "massive",
    "pandas_market_calendars",
    "fredapi",
    "edgartools",
    "quantstats",
    "dash",
    "pitindex",
    "mlx_lm",
]

html_theme = "furo"
html_title = "tam"
